<script setup lang="ts">
import { ref, onMounted, nextTick } from 'vue'
import { useRouter } from 'vue-router'
import { toast } from 'vue-sonner'
import { api } from '../composables/useApi'
import { useBudget } from '../composables/useBudget'
import { useProductSearch } from '../composables/useProductSearch'
import type { Client, CompanyInfo } from '../types'

import SkeletonLoader from '../shared/ui/SkeletonLoader.vue'
import BudgetStepBar from '../components/budget/BudgetStepBar.vue'
import BudgetHeader from '../components/budget/BudgetHeader.vue'
import BudgetInspection from '../components/budget/BudgetInspection.vue'
import BudgetClientSection from '../components/budget/BudgetClientSection.vue'
import BudgetItemsTable from '../components/budget/BudgetItemsTable.vue'
import BudgetTotals from '../components/budget/BudgetTotals.vue'
import BudgetNotes from '../components/budget/BudgetNotes.vue'
import BudgetImages from '../components/budget/BudgetImages.vue'
import BudgetActions from '../components/budget/BudgetActions.vue'

const props = defineProps<{ id?: string }>()
const router = useRouter()

const STEPS = ['Empresa', 'Cliente', 'Inspección', 'Detalle', 'Finalizar']
const currentStep = ref(1)
const budgetContainerRef = ref<HTMLElement | null>(null)
const exportingPdf = ref(false)

const {
  company, client, correlativo, logo, notes, sections, images, saving, today,
  neto, iva, total,
  addRow, removeRow, addSection, removeSection, updateSectionTitle,
  visitFindings, visitSummary, preliminaryWorks,
  addFinding, removeFinding, updateFinding,
  addFindingImages, removeFindingImage, updateFindingImageCaption,
  addWork, removeWork, updateWork,
  addImages, removeImage, updateImageCaption,
  handleLogoChange,
  loadBudget, saveDraft, saveBudget, status,
} = useBudget()

const { searchResults, activeSectionIndex, activeRowIndex, search, pick, close } = useProductSearch()

const clients = ref<Client[]>([])
const loading = ref(true)

function updateCompanyField(field: keyof CompanyInfo, value: string) {
  company[field] = value
}

function selectClient(c: Client) {
  Object.assign(client, c)
}

function updateClientField(field: string, value: string) {
  ;(client as Record<string, unknown>)[field] = value
}

function updateItem(sectionIndex: number, rowIndex: number, field: string, value: string | number) {
  ;(sections.value[sectionIndex].items[rowIndex] as Record<string, unknown>)[field] = value
}

function pickProduct(product: Parameters<typeof pick>[0], sectionIndex: number, rowIndex: number) {
  pick(product, sections.value[sectionIndex].items[rowIndex])
}

function handlePrint() {
  window.print()
}

async function handleExportPdf() {
  const html2pdf = (await import('html2pdf.js')).default
  exportingPdf.value = true
  await nextTick()

  const element = budgetContainerRef.value
  if (!element) {
    exportingPdf.value = false
    return
  }

  const clientName = client.name || 'presupuesto'
  const filename = `presupuesto-${clientName.toLowerCase().replace(/\s+/g, '-')}-${new Date().toISOString().slice(0, 10)}.pdf`

  await html2pdf()
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    .set({
      margin: [10, 10, 10, 10],
      filename,
      image: { type: 'jpeg', quality: 0.95 },
      html2canvas: {
          scale: 2,
          useCORS: true,
          logging: false,
          onclone: async (_clonedDoc: Document, _clonedElement: HTMLElement) => {
            // html2canvas has its own CSS parser that fails on color-mix(in oklab/oklch, ...)
            // generated by Tailwind 4 for opacity modifiers (e.g. bg-brand-500/20).
            //
            // Strategy:
            //   1. Resolve CSS var() references using getComputedStyle on the original root
            //   2. Convert every color-mix(in oklab/oklch, ...) occurrence to rgba()
            //   3. Process <style> tags (dev mode) AND fetch+replace <link> sheets (prod mode)
            //      so that html2canvas never encounters an unsupported color function.

            const rootStyle = window.getComputedStyle(document.documentElement)

            // Resolve var(--name, fallback) up to 3 levels deep
            const resolveVar = (expr: string): string => {
              let value = expr.trim()
              for (let i = 0; i < 3; i++) {
                if (!value.startsWith('var(')) break
                const m = value.match(/^var\(\s*(--[\w-]+)\s*(?:,\s*([\s\S]+?))?\s*\)$/)
                if (!m) break
                value = rootStyle.getPropertyValue(m[1]).trim() || m[2]?.trim() || value
              }
              return value
            }

            const NAMED: Record<string, string> = { white: '#ffffff', black: '#000000' }

            // Convert a color expression + opacity percentage to rgba()
            const toRgba = (colorExpr: string, pct: string): string => {
              let color = resolveVar(colorExpr)
              color = NAMED[color.toLowerCase()] ?? color
              const a = (parseFloat(pct) / 100).toFixed(3)
              if (color.startsWith('#')) {
                const h = color.length === 4
                  ? `${color[1]}${color[1]}${color[2]}${color[2]}${color[3]}${color[3]}`
                  : color.slice(1, 7)
                const r = parseInt(h.slice(0, 2), 16)
                const g = parseInt(h.slice(2, 4), 16)
                const b = parseInt(h.slice(4, 6), 16)
                return `rgba(${r},${g},${b},${a})`
              }
              // Safe fallback: fully transparent so it doesn't distort the layout
              return `rgba(0,0,0,0)`
            }

            // Handles both arg orderings:
            //   color-mix(in oklab, <COLOR> <PCT>%, transparent)
            //   color-mix(in oklab, transparent, <COLOR> <PCT>%)
            // Color token: allows parentheses inside (e.g. rgb(r,g,b)) via [^()]*
            const COLOR_TOKEN = '(?:[^,()]+|\\([^)]*\\))+'
            const COLOR_MIX_RE = new RegExp(
              `color-mix\\(\\s*in\\s+ok(?:lab|lch)\\s*,\\s*` +
              `(?:(${COLOR_TOKEN})\\s+([\\d.]+)%\\s*,\\s*transparent` +
              `|transparent\\s*,\\s*(${COLOR_TOKEN})\\s+([\\d.]+)%)\\s*\\)`,
              'gi',
            )

            const fixCss = (css: string): string =>
              css.replace(COLOR_MIX_RE, (_m, c1, p1, c2, p2) =>
                toRgba(c1 ?? c2, p1 ?? p2),
              )

            // 1. Fix inline <style> tags (Vite dev mode / SSR inlined CSS)
            _clonedDoc.querySelectorAll('style').forEach(el => {
              el.textContent = fixCss(el.textContent ?? '')
            })

            // 2. Fetch external <link rel="stylesheet"> and re-inject as fixed <style>
            //    (Vite production build extracts CSS to separate .css files)
            const links = Array.from(
              _clonedDoc.querySelectorAll<HTMLLinkElement>('link[rel="stylesheet"]'),
            )
            await Promise.all(links.map(async link => {
              try {
                const res = await fetch(link.href)
                const css = fixCss(await res.text())
                const style = _clonedDoc.createElement('style')
                style.textContent = css
                link.replaceWith(style)
              } catch {
                // If fetch fails, remove the link so html2canvas doesn't try to parse it
                link.remove()
              }
            }))
          },
        },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
      pagebreak: { mode: ['avoid-all', 'css', 'legacy'] },
    } as any)
    .from(element)
    .save()

  exportingPdf.value = false
}

async function handleSaveDraft() {
  const result = await saveDraft(currentStep.value)
  if (result !== false) {
    toast.success('Borrador guardado')
    if (!props.id) {
      router.replace(`/presupuestos/${result}`)
    }
  }
}

async function handleSave() {
  const ok = await saveBudget(props.id)
  if (ok) {
    toast.success('Presupuesto guardado correctamente')
    router.push('/presupuestos')
  }
}

onMounted(async () => {
  try {
    clients.value = await api.get('/clients')
    if (props.id) {
      const savedStep = await loadBudget(props.id)
      if (status.value === 'borrador' && savedStep) {
        currentStep.value = savedStep
      }
    }
  } finally {
    loading.value = false
  }
})
</script>

<template>
  <!-- Skeleton inicial mientras cargan clientes / presupuesto existente -->
  <div v-if="loading" class="mx-auto max-w-[210mm] space-y-4 p-8">
    <SkeletonLoader height="h-24" />
    <SkeletonLoader height="h-16" />
    <SkeletonLoader height="h-64" />
  </div>

  <div v-else class="relative print:p-0" :class="{ 'pdf-exporting': exportingPdf }">
    <!-- Marca de agua -->
    <div class="hidden print:flex fixed inset-0 z-0 items-center justify-center pointer-events-none">
      <img
        src="/img/site-engineer-construction-site.jpg"
        alt=""
        class="w-full h-full object-cover object-center opacity-[0.06] grayscale mix-blend-multiply"
      />
    </div>

    <div ref="budgetContainerRef" class="relative z-10 max-w-[210mm] mx-auto bg-white print:bg-transparent shadow-lg print:shadow-none rounded-xl print:rounded-none p-8 print:p-0">

      <!-- Breadcrumb steps -->
      <BudgetStepBar v-show="!exportingPdf" :steps="STEPS" :current="currentStep" @goto="currentStep = $event" />

      <!-- ── STEP 1: Empresa ── -->
      <div v-show="currentStep === 1 || exportingPdf" class="print:!block">
        <BudgetHeader
          :company="company"
          :logo="logo"
          :date="today"
          :correlativo="correlativo"
          @update:company="updateCompanyField"
          @update:logo="handleLogoChange"
        />
        <div class="no-print flex justify-end gap-3 mt-6">
          <button class="px-5 py-2.5 border border-amber-300 text-amber-700 text-sm font-semibold rounded-lg hover:bg-amber-50 dark:border-amber-600 dark:text-amber-400 dark:hover:bg-amber-500/10 transition-colors" :disabled="saving" @click="handleSaveDraft">
            {{ saving ? 'Guardando...' : 'Guardar borrador' }}
          </button>
          <button class="px-5 py-2.5 bg-brand-800 text-white text-sm font-semibold rounded-lg hover:bg-brand-900 transition-colors" @click="currentStep = 2">
            Siguiente →
          </button>
        </div>
      </div>

      <!-- ── STEP 2: Cliente ── -->
      <div v-show="currentStep === 2 || exportingPdf" class="print:!block">
        <BudgetClientSection
          :client="client"
          :clients="clients"
          @select-client="selectClient"
          @update:field="updateClientField"
        />
        <div class="no-print flex justify-between mt-6">
          <button class="px-5 py-2.5 border border-zinc-300 text-zinc-600 text-sm font-semibold rounded-lg hover:bg-zinc-50 dark:border-zinc-700 dark:text-zinc-400 dark:hover:bg-zinc-800 transition-colors" @click="currentStep = 1">
            ← Anterior
          </button>
          <button class="px-5 py-2.5 border border-amber-300 text-amber-700 text-sm font-semibold rounded-lg hover:bg-amber-50 dark:border-amber-600 dark:text-amber-400 dark:hover:bg-amber-500/10 transition-colors" :disabled="saving" @click="handleSaveDraft">
            {{ saving ? 'Guardando...' : 'Guardar borrador' }}
          </button>
          <button class="px-5 py-2.5 bg-brand-800 text-white text-sm font-semibold rounded-lg hover:bg-brand-900 transition-colors" @click="currentStep = 3">
            Siguiente →
          </button>
        </div>
      </div>

      <!-- ── STEP 3: Inspección ── -->
      <div v-show="currentStep === 3 || exportingPdf" class="print:!block">
        <BudgetInspection
          :findings="visitFindings"
          :summary="visitSummary"
          :works="preliminaryWorks"
          @add-finding="addFinding"
          @remove-finding="removeFinding"
          @update-finding="updateFinding"
          @add-finding-images="addFindingImages"
          @remove-finding-image="removeFindingImage"
          @update-finding-image-caption="updateFindingImageCaption"
          @update:summary="visitSummary = $event"
          @add-work="addWork"
          @remove-work="removeWork"
          @update-work="updateWork"
        />
        <div class="no-print flex justify-between mt-6">
          <button class="px-5 py-2.5 border border-zinc-300 text-zinc-600 text-sm font-semibold rounded-lg hover:bg-zinc-50 dark:border-zinc-700 dark:text-zinc-400 dark:hover:bg-zinc-800 transition-colors" @click="currentStep = 2">
            ← Anterior
          </button>
          <button class="px-5 py-2.5 border border-amber-300 text-amber-700 text-sm font-semibold rounded-lg hover:bg-amber-50 dark:border-amber-600 dark:text-amber-400 dark:hover:bg-amber-500/10 transition-colors" :disabled="saving" @click="handleSaveDraft">
            {{ saving ? 'Guardando...' : 'Guardar borrador' }}
          </button>
          <button class="px-5 py-2.5 bg-brand-800 text-white text-sm font-semibold rounded-lg hover:bg-brand-900 transition-colors" @click="currentStep = 4">
            Siguiente →
          </button>
        </div>
      </div>

      <!-- ── STEP 4: Detalle ── -->
      <div v-show="currentStep === 4 || exportingPdf" class="print:!block">
        <BudgetItemsTable
          v-for="(section, si) in sections"
          :key="si"
          :section-index="si"
          :title="section.title"
          :items="section.items"
          :search-results="searchResults"
          :active-section-index="activeSectionIndex"
          :active-row-index="activeRowIndex"
          :can-remove="sections.length > 1"
          @search="search"
          @pick="pickProduct"
          @close-search="close"
          @add-row="addRow"
          @remove-row="removeRow"
          @update-item="updateItem"
          @update-title="updateSectionTitle"
          @remove-section="removeSection"
        />

        <div class="no-print mb-4">
          <button
            class="text-sm text-zinc-500 hover:text-brand-700 border border-dashed border-zinc-300 hover:border-brand-400 dark:border-zinc-700 dark:text-zinc-400 dark:hover:border-brand-600 rounded-lg px-4 py-2 transition-colors w-full"
            @click="addSection"
          >
            + Agregar sección
          </button>
        </div>

        <BudgetTotals :neto="neto" :iva="iva" :total="total" />

        <div class="no-print flex justify-between mt-6">
          <button class="px-5 py-2.5 border border-zinc-300 text-zinc-600 text-sm font-semibold rounded-lg hover:bg-zinc-50 dark:border-zinc-700 dark:text-zinc-400 dark:hover:bg-zinc-800 transition-colors" @click="currentStep = 3">
            ← Anterior
          </button>
          <button class="px-5 py-2.5 border border-amber-300 text-amber-700 text-sm font-semibold rounded-lg hover:bg-amber-50 dark:border-amber-600 dark:text-amber-400 dark:hover:bg-amber-500/10 transition-colors" :disabled="saving" @click="handleSaveDraft">
            {{ saving ? 'Guardando...' : 'Guardar borrador' }}
          </button>
          <button class="px-5 py-2.5 bg-brand-800 text-white text-sm font-semibold rounded-lg hover:bg-brand-900 transition-colors" @click="currentStep = 5">
            Siguiente →
          </button>
        </div>
      </div>

      <!-- ── STEP 5: Finalizar ── -->
      <div v-show="currentStep === 5 || exportingPdf" class="print:!block">
        <BudgetImages
          title="Diseños y Renders (opcional)"
          :images="images"
          @add="addImages"
          @remove="removeImage"
          @update-caption="updateImageCaption"
        />

        <BudgetNotes v-model="notes" />

        <div class="no-print flex justify-between mt-6 mb-4">
          <button class="px-5 py-2.5 border border-zinc-300 text-zinc-600 text-sm font-semibold rounded-lg hover:bg-zinc-50 dark:border-zinc-700 dark:text-zinc-400 dark:hover:bg-zinc-800 transition-colors" @click="currentStep = 4">
            ← Anterior
          </button>
          <button class="px-5 py-2.5 border border-amber-300 text-amber-700 text-sm font-semibold rounded-lg hover:bg-amber-50 dark:border-amber-600 dark:text-amber-400 dark:hover:bg-amber-500/10 transition-colors" :disabled="saving" @click="handleSaveDraft">
            {{ saving ? 'Guardando...' : 'Guardar borrador' }}
          </button>
        </div>

        <BudgetActions :saving="saving" @save="handleSave" @print="handlePrint" @pdf="handleExportPdf" />
      </div>

      <!-- Pie de página (solo print y PDF) -->
      <div class="print-section hidden print:block mt-8 pt-4 border-t border-zinc-300 text-center">
        <p class="text-xs text-zinc-400">{{ company.name }} &middot; {{ company.rut }} &middot; {{ company.phone }}</p>
      </div>
    </div>
  </div>
</template>

<style scoped>
.pdf-exporting :deep(.no-print) {
  display: none !important;
}
.pdf-exporting .print-section {
  display: block !important;
}
</style>
